// Fafi 27 - akıllı tahta dokunmatik kontrol katmanı
(function(){'use strict';
 const root=document.getElementById('touchPad'); let game=null,visible=false; const sticks=new Map(),timers=new Map();
 const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>Array.from(r.querySelectorAll(s)), clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
 const move=(t,x,z)=>game&&game.setMove(t,clamp(x,-1,1),clamp(z,-1,1)); const press=(t,b,d,o={})=>game&&game.press(t,b,d,o);
 $$('.tp-stick').forEach(el=>{const t=+el.closest('.tp-side').dataset.team; const end=e=>{if(sticks.get(t)!==e.pointerId)return;sticks.delete(t);el.releasePointerCapture?.(e.pointerId);$('.tp-knob',el).style.transform='translate(0,0)';move(t,0,0)}; const mv=e=>{if(sticks.get(t)!==e.pointerId)return;const r=el.getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),m=r.width*.34,d=Math.hypot(dx,dy),k=d?Math.min(1,m/d):0;$('.tp-knob',el).style.transform=`translate(${dx*k}px,${dy*k}px)`;move(t,dx*k/m,dy*k/m)};el.addEventListener('pointerdown',e=>{e.preventDefault();sticks.set(t,e.pointerId);el.setPointerCapture(e.pointerId);mv(e)});el.addEventListener('pointermove',mv);el.addEventListener('pointerup',end);el.addEventListener('pointercancel',end)});
 $$('.tp-btn').forEach(btn=>{const start=e=>{e.preventDefault();const t=+btn.closest('.tp-side').dataset.team,b=btn.dataset.btn;btn.classList.add('on');if(b==='sprint'||b==='pressure'||b==='switch'||b==='slide'){press(t,b,true);return}timers.set(t+':'+b,performance.now());press(t,b,true)};const end=e=>{e.preventDefault();const t=+btn.closest('.tp-side').dataset.team,b=btn.dataset.btn;btn.classList.remove('on');if(b==='sprint'||b==='pressure'||b==='switch'||b==='slide'){if(b==='sprint'||b==='pressure')press(t,b,false);return}const st=timers.get(t+':'+b)||performance.now();timers.delete(t+':'+b);press(t,b,false,{hold:clamp((performance.now()-st)/1000,0,1.2)})};btn.addEventListener('pointerdown',start);btn.addEventListener('pointerup',end);btn.addEventListener('pointercancel',end)});
 window.FafiTouch={show(o={}){game=o.game||game;visible=true;root.classList.add('on');root.setAttribute('aria-hidden','false')},hide(){visible=false;root.classList.remove('on');root.setAttribute('aria-hidden','true');sticks.clear();timers.clear();move(0,0,0);move(1,0,0)},isVisible(){return visible}};
})();
